//
// Created by 李研 on 2019/7/12.
//

#ifndef BEAUTYOFDATASTRUCTUREANDALGORITHM_LINKEDLIST_H
#define BEAUTYOFDATASTRUCTUREANDALGORITHM_LINKEDLIST_H


class LinkedList {

};


#endif //BEAUTYOFDATASTRUCTUREANDALGORITHM_LINKEDLIST_H
